---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Dashboard"
subtitle: "Exceptionerror.io"
#logo: "logo.png"
icon: "fas fa-sm fa-network-wired" # Optional icon.
header: false
#footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.
footer: ''
links:
  - name: "Exceptionerror.io"
    url: "https://exceptionerror.io"
#   - name: "Login"
#     icon: "fas fa-sign-in-alt"
#     url: "https://auth.exceptionerror.io/auth/realms/master/account"
#     target: "_blank" 
services:
  - name: "Services"
    icon: "fas fa-cloud"
    items:
#       - name: "Nextcloud"
#         logo: "assets/tools/nextcloud.png"
#         subtitle: "File share and collaboration platform"
#         tag: "app"
#         url: "https://cloud.exceptionerror.io/"
#         target: "_blank" 
      - name: "Blog"
        logo: "assets/tools/ghost.jpg"
        subtitle: "Collection of thoughts, stories and ideas"
        tag: "blog"
        url: "https://blog.exceptionerror.io/"
        target: "_blank" 
      - name: "Gallery"
        logo: "assets/tools/gallery.png"
        subtitle: "Public Collection of photos on my travels"
        tag: "gallery"
        url: "https://gallery.exceptionerror.io/"
        target: "_blank"
      - name: "Bitwarden"
        logo: "assets/tools/bitwarden.png"
        subtitle: "Password Manager"
        tag: "gallery"
        url: "https://bitwarden.exceptionerror.io/"
        target: "_blank"
        
#   - name: "DevOPS Applications"
#     icon: "fas fa-laptop-code"
#     items:
#       - name: "Gittea"
#         logo: "assets/tools/gitea.png"
#         subtitle: "Git with a cup of tea"
#         tag: "app"
#         url: "https://git.exceptionerror.io/"
#         target: "_blank" 
#       - name: "Drone"
#         logo: "assets/tools/drone.svg"
#         subtitle: "Drone CI Server"
#         tag: "app"
#         url: "https://drone.exceptionerror.io/"
#         target: "_blank" 
  
#   - name: "Monitoring"
#     icon: "fas fa-chart-area"
#     items:
#       - name: "Monitoring"
#         logo: "assets/tools/grafana.png"
#         subtitle: "Service Monitoring"
#         tag: "app"
#         url: "https://grafana.exceptionerror.io/"
#         target: "_blank" 
#       - name: "Status"
#         logo: "assets/tools/uptimerobot.svg"
#         subtitle: "Check the uptime of the service"
#         tag: "app"
#         url: "https://Status.exceptionerror.io/"
#         target: "_blank" 
      
  - name: "Collaboration"
    icon: "fas fa-user-friends"
    items:
      - name: "Element"
        logo: "assets/tools/element.jpg"
        subtitle: "Element chat "
        tag: "meeting"
        url: "https://element.exceptionerror.io/"
        target: "_blank" 
      - name: "Watch2Gether"
        logo: "assets/tools/watch2gether.png"
        subtitle: "Watch things together"
        tag: "app"
        url: "https://watch2gether.exceptionerror.io/"
        target: "_blank" 
