replicaCount: 1
image:
  repository: ghcr.io/robrotheram/portal
  pullPolicy: Always
  tag: latest
  commit: 52984607b682b1b7f6d170f657cf357e42a2c886
imagePullSecrets: []
nameOverride: ''
fullnameOverride: exceptionerror-io
podAnnotations: {}
service:
  port: 3000
ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: letsencrypt-production
  hosts:
    - host: exceptionerror.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - exceptionerror.io
      secretName: production-portal-tls
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
