replicaCount: 1
image:
  repository: ghcr.io/robrotheram/portal
  pullPolicy: Always
  tag: latest
  commit: 5c56701b7959826cbf3091c0b84c02ba26e08b54
imagePullSecrets: []
nameOverride: ''
fullnameOverride: exceptionerror-io
podAnnotations: {}
service:
  port: 3000
ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: letsencrypt-production
  hosts:
    - host: exceptionerror.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - exceptionerror.io
      secretName: production-blog-tls
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
