name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build docker container
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
        
    - name: Build the Docker image
      run: |
        docker build . --tag ghcr.io/robrotheram/blog:latest
        docker push ghcr.io/robrotheram/blog:latest

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    name: update the helm
    steps:
     - uses: actions/checkout@v2
     - name: Update values.yaml
       uses: fjogeleit/yaml-update-action@master
       with:
          valueFile: 'helm/values.yaml'
          propertyPath: 'image.commit'
          value: ${{ github.sha }}
          branch: 'main'
          commitChange: true
          updateFile: true
          message: "Update Helm"
